#!/usr/bin/env bash
# Renders k8s/secret.yaml from the git-ignored .env.
#
# Only the genuinely sensitive keys are copied; everything else lives in the
# committed ConfigMap (k8s/10-config.yaml). The output file is git-ignored, so
# real keys never reach a commit - see k8s/secrets.example.yaml for the shape.
set -euo pipefail
cd "$(dirname "$0")/.."

[ -f .env ] || {
  echo "error: .env not found. Run scripts/env-init.sh first." >&2
  exit 1
}

python - <<'PY'
import io, os, sys

# Sensitive keys only. Anything not listed here belongs in the ConfigMap.
SECRET_KEYS = [
    "POSTGRES_PASSWORD",
    "JWT_SECRET",
    "BULLBOARD_PASSWORD",
    "ANTHROPIC_API_KEY",
    "OPENAI_API_KEY",
]
# Keys the app refuses to start without.
REQUIRED = {"POSTGRES_PASSWORD", "JWT_SECRET", "BULLBOARD_PASSWORD"}

values = {}
with io.open(".env", encoding="utf-8") as fh:
    for line in fh:
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if key in SECRET_KEYS:
            values[key] = value.strip().strip('"').strip("'")

missing = sorted(k for k in REQUIRED if not values.get(k))
if missing:
    sys.exit("error: .env is missing required secrets: " + ", ".join(missing))

def quote(v):
    # YAML single-quoted scalar: the only escape needed is a doubled quote.
    return "'" + v.replace("'", "''") + "'"

lines = [
    "# GENERATED by scripts/k8s-secret.sh from .env - DO NOT COMMIT.",
    "# This file is git-ignored. The tracked template is k8s/secrets.example.yaml.",
    "apiVersion: v1",
    "kind: Secret",
    "metadata:",
    "  name: app-secrets",
    "  namespace: news-hub",
    "type: Opaque",
    "stringData:",
]
for key in SECRET_KEYS:
    lines.append("  {}: {}".format(key, quote(values.get(key, ""))))

with io.open("k8s/secret.yaml", "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(lines) + "\n")

present = [k for k in SECRET_KEYS if values.get(k)]
print("[k8s-secret] wrote k8s/secret.yaml with keys: " + ", ".join(present))
empty = [k for k in SECRET_KEYS if not values.get(k)]
if empty:
    print("[k8s-secret] note: empty (optional) keys: " + ", ".join(empty))
PY

# Belt and braces: refuse to continue if the generated file is somehow tracked.
if git ls-files --error-unmatch k8s/secret.yaml >/dev/null 2>&1; then
  echo "error: k8s/secret.yaml is tracked by git. Untrack it before deploying." >&2
  exit 1
fi
